### ISSUE TITLE
Retention Period

### ISSUE THREAD

**Issue by olgunkaya** [theurichde/kowl#1]
Hi,

First of all, thanks for this great tool. We have got our old visualizer UI retired with the help of this tool.

My question (not an issue, and sorry if this an inappropriate location to ask) is; what is the retention policy of the tool ? How far can I go back in the history ? Is there a configuration parameter for retention ?

**Comment by theurichde** [comment]
Hi there. This repository only acts as archive for Kowl before chaning to the Redpanda Licencse. I will not put any work into the repository. Sorry!
