### ISSUE TITLE
Bitbucket connection

### ISSUE THREAD

**Issue by fpernas** [theurichde/kowl#2]
Hey. I'm trying to connect Kowl with bitbucket to pull the Proto files, but I'm getting `different` errors and I'm unable to make it work (I have to use the filesystem part but it's not desirable). I'm running Kowl on a docker container

I have the repo url configured as: https://bitbucket.org/company-name/repo-name.git

With the git.enabled in true, I tried to set "basicAuth" sending the username and password in plain text, but I'm getting 
`{"level":"fatal","ts":"2024-03-22T19:16:17.551Z","msg":"failed to start kafka service","error":"failed to start git service: failed to clone git repo: authentication required"}`

If instead I use the "ssh" config, on "privateKeyFilePath" I point to the directory where the private key is located, but I'm getting this error instead: 
`{"level":"fatal","ts":"2024-03-22T19:16:03.042Z","msg":"failed to start kafka service","error":"failed to start git service: failed to clone git repo: invalid auth method"}`

Just in case, this is the whole log Docker shows:

```
kowl  | {"level":"info","ts":"2024-03-22T19:16:14.829Z","msg":"started Kowl","version":"v1.5.0","git_sha":"598117cf7d3ef49e82ad9e7424a08858b3e60216","built":"2021-11-10T21:41:16Z"}
kowl  | {"level":"info","ts":"2024-03-22T19:16:14.829Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
kowl  | {"level":"info","ts":"2024-03-22T19:16:16.638Z","msg":"successfully connected to kafka cluster","advertised_broker_count":1,"topic_count":296,"controller_id":0,"kafka_version":"v2.4"}
kowl  | {"level":"info","ts":"2024-03-22T19:16:16.638Z","msg":"creating Kafka connect HTTP clients and testing connectivity to all clusters"}
kowl  | {"level":"info","ts":"2024-03-22T19:16:16.638Z","msg":"tested Kafka connect cluster connectivity","successful_clusters":0,"failed_clusters":0}
kowl  | {"level":"info","ts":"2024-03-22T19:16:16.638Z","msg":"successfully create Kafka connect service"}
kowl  | {"level":"info","ts":"2024-03-22T19:16:16.638Z","msg":"cloning git repository","repository_url":"https://bitbucket.org/company-name/repo-name.git","url":"https://bitbucket.org/company-name/repo-name.git"}
kowl  | {"level":"fatal","ts":"2024-03-22T19:16:17.551Z","msg":"failed to start kafka service","error":"failed to start git service: failed to clone git repo: authentication required"}
kowl exited with code 0
```

Can you give me a hand? Am I configuring something wrong?

**Comment by theurichde** [comment]
Hi there. This repository only acts as archive for Kowl before chaning to the Redpanda Licencse. I will not put any work into the repository. Sorry!
